"""Initial

Revision ID: 7207df86f088
Revises: 529e8c23bdc6
Create Date: 2023-04-28 12:25:57.358746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7207df86f088'
down_revision = '529e8c23bdc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
