"""add SimCard

Revision ID: 73ba916bd1c6
Revises: 7207df86f088
Create Date: 2024-07-04 15:18:29.000350

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '73ba916bd1c6'
down_revision = '7207df86f088'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('contracts_id', sa.Integer(), nullable=False),
    sa.Column('yoda_contract_id', sa.String(length=36), nullable=False),
    sa.Column('name_contract', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('contracts_id')
    )
    op.create_table('equipments',
    sa.Column('equipments_id', sa.Integer(), nullable=False),
    sa.Column('yoda_networkequipments_id', sa.String(length=36), nullable=False),
    sa.Column('yoda_task_id', sa.String(length=36), nullable=False),
    sa.Column('number_equipment', sa.String(length=30), nullable=False),
    sa.Column('type_equipment', sa.String(length=30), nullable=False),
    sa.Column('model_equipment', sa.String(length=150), nullable=False),
    sa.Column('latitude', sa.String(length=20), nullable=False),
    sa.Column('longitude', sa.String(length=20), nullable=False),
    sa.Column('number_sim_1', sa.String(length=11), nullable=True),
    sa.Column('iccid_1', sa.String(length=20), nullable=True),
    sa.Column('operator_1', sa.String(length=20), nullable=True),
    sa.Column('number_sim_2', sa.String(length=11), nullable=True),
    sa.Column('iccid_2', sa.String(length=20), nullable=True),
    sa.Column('operator_2', sa.String(length=20), nullable=True),
    sa.Column('number_sim_3', sa.String(length=11), nullable=True),
    sa.Column('iccid_3', sa.String(length=20), nullable=True),
    sa.Column('operator_3', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('equipments_id')
    )
    op.create_table('users',
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('user_id_tg', sa.BigInteger(), nullable=False),
    sa.Column('tg_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('update_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('users_id')
    )
    op.create_table('logmessage',
    sa.Column('logmessage_id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('type_message', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['users_id'], ['users.users_id'], ),
    sa.PrimaryKeyConstraint('logmessage_id')
    )
    op.alter_column('importsimslog', 'state',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.add_column('simcards', sa.Column('simcards_id', sa.Integer(), nullable=False))
    op.alter_column('simcards', 'operator',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('simcards', 'iccid',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('simcards', 'msisdn',
               existing_type=sa.VARCHAR(length=11),
               nullable=False)
    op.alter_column('simcards', 'ip',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
    op.alter_column('simcards', 'date_receipt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('simcards', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('simcards_id_idx', table_name='simcards')
    op.drop_column('simcards', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('simcards', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('simcards_id_idx', 'simcards', ['id', 'iccid', 'msisdn'], unique=False)
    op.alter_column('simcards', 'created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('simcards', 'date_receipt',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('simcards', 'ip',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
    op.alter_column('simcards', 'msisdn',
               existing_type=sa.VARCHAR(length=11),
               nullable=True)
    op.alter_column('simcards', 'iccid',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('simcards', 'operator',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_column('simcards', 'simcards_id')
    op.alter_column('importsimslog', 'state',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_table('logmessage')
    op.drop_table('users')
    op.drop_table('equipments')
    op.drop_table('contracts')
    # ### end Alembic commands ###
