"""Initial

Revision ID: 840130885b44
Revises: d9b79e1e8359
Create Date: 2023-03-16 12:58:10.809929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '840130885b44'
down_revision = 'd9b79e1e8359'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sims', sa.Column('imei', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sims', 'imei')
    # ### end Alembic commands ###
