"""Initial

Revision ID: d9b79e1e8359
Revises: 
Create Date: 2023-03-14 21:44:21.658913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b79e1e8359'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('importsimslog',
    sa.Column('importsimslog_id', sa.Integer(), nullable=False),
    sa.Column('start_import', sa.DateTime(), nullable=False),
    sa.Column('name_file', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('count_import_sim', sa.Integer(), nullable=False),
    sa.Column('error_import', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('importsimslog_id')
    )
    op.create_table('sims',
    sa.Column('sims_id', sa.BigInteger(), nullable=False),
    sa.Column('number_tel', sa.String(length=11), nullable=False),
    sa.Column('iccid', sa.String(length=20), nullable=False),
    sa.Column('apn', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('activity', sa.DateTime(), nullable=True),
    sa.Column('traffic', sa.String(length=15), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('update_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sims_id')
    )
    op.create_table('updatesimlog',
    sa.Column('updatesimlog_id', sa.BigInteger(), nullable=False),
    sa.Column('sims_id', sa.BigInteger(), nullable=True),
    sa.Column('importsimslog_id', sa.Integer(), nullable=True),
    sa.Column('number_tel', sa.String(length=11), nullable=True),
    sa.Column('iccid', sa.String(length=20), nullable=True),
    sa.Column('apn', sa.Text(), nullable=True),
    sa.Column('ip', sa.String(length=15), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('activity', sa.DateTime(), nullable=True),
    sa.Column('traffic', sa.String(length=15), nullable=True),
    sa.Column('operator', sa.String(length=20), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['importsimslog_id'], ['importsimslog.importsimslog_id'], ),
    sa.ForeignKeyConstraint(['sims_id'], ['sims.sims_id'], ),
    sa.PrimaryKeyConstraint('updatesimlog_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('updatesimlog')
    op.drop_table('sims')
    op.drop_table('importsimslog')
    # ### end Alembic commands ###
