"""Initial

Revision ID: fd81b0b8a8fd
Revises: 840130885b44
Create Date: 2023-03-16 13:55:47.314717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd81b0b8a8fd'
down_revision = '840130885b44'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sims', sa.Column('state_in_lk', sa.String(length=15), nullable=False))
    op.add_column('sims', sa.Column('last_upload', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sims', 'last_upload')
    op.drop_column('sims', 'state_in_lk')
    # ### end Alembic commands ###
